"""Proactive notification model — alerts delivered to users."""

from odoo import fields, models


SEVERITY_SELECTION = [
    ('info', 'Info'),
    ('warning', 'Warning'),
    ('critical', 'Critical'),
]

CHANNEL_SELECTION = [
    ('in_app', 'In-app'),
    ('email', 'Email'),
    ('whatsapp', 'WhatsApp'),
    ('sms', 'SMS'),
]


class ProactiveNotification(models.Model):
    """Notification generated by a proactive watcher."""

    _name = 'telecom.proactive.notification'
    _description = 'Proactive Notification'
    _order = 'create_date desc'

    watcher_id = fields.Many2one(
        'telecom.proactive.watcher',
        string='Watcher',
        required=True,
        ondelete='cascade',
        index=True,
    )
    user_id = fields.Many2one(
        'res.users',
        string='Recipient',
        required=True,
        index=True,
    )
    title = fields.Char(
        string='Title',
        required=True,
    )
    message = fields.Text(
        string='Message',
    )
    severity = fields.Selection(
        selection=SEVERITY_SELECTION,
        string='Severity',
        default='info',
        required=True,
    )
    is_read = fields.Boolean(
        string='Read',
        default=False,
    )
    record_model = fields.Char(
        string='Source Model',
        help="Model name of the record that triggered the notification",
    )
    record_id = fields.Integer(
        string='Source Record ID',
        help="ID of the record that triggered the notification",
    )
    channel = fields.Selection(
        selection=CHANNEL_SELECTION,
        string='Channel',
        default='in_app',
        required=True,
    )

    def action_mark_read(self):
        """Mark notification as read."""
        self.write({'is_read': True})

    def action_open_source(self):
        """Open the source record in a form view."""
        self.ensure_one()
        if self.record_model and self.record_id:
            return {
                'type': 'ir.actions.act_window',
                'res_model': self.record_model,
                'res_id': self.record_id,
                'view_mode': 'form',
                'target': 'current',
            }
        return False
